### ISSUE TITLE
Add header:false to grit bin example?

### ISSUE THREAD

**Issue by slowe** [Swirrl/csvw.org#6]
I'm new to looking at CSVW after your ODI Lunchtime Lecture but noted that the example grit bin data from Data Mill North doesn't have a header row. After looking around on [the W3C page](https://www.w3.org/TR/tabular-data-primer/#h-dialects) it looks as though it assumes there will be one header row so would the example lose the first row of `grit_bins.csv`? If I've understood the W3C page correctly, adding the following would keep the first row:

```
"dialect": {
    "header": false
}
```

Is it necessary or worth explicitly including that in the example on either the front page or the [
How to make CSVW](https://csvw.org/guides/how-to-make-csvw.html) page?

**Comment by Robsteranium** [comment]
Sorry for the slow response!

You're quite right, the default dialect assumes a header row which we don't have here. I'll update the index page and how-to guide.
