### ISSUE TITLE
Add cldf/csvw to tools

### ISSUE THREAD

**Issue by Robsteranium** [Swirrl/csvw.org#7]
Per Robsteranium/csvwr#5.

**Comment by xrotwang** [comment]
I spent the last week looking into cldf/csvw and spec compliance again, and in particular adding `to_json` functionality that passes all but one test of the ToJson test suite. That's not released yet, though. I'd say adding cldf/csvw to the tools section here should wait for this release - which will be soon, hopefully within the next week.

**Comment by xrotwang** [comment]
Just released csvw 3.0 (https://pypi.org/project/csvw/) adding a lot in terms of CSVW spec conformance, e.g. CLI for [csvw2json](https://github.com/cldf/csvw#csvw2json). So with that in place, I think it could be added to csvw.org
